title: Yucleic Lab
description: Nucleic acids chemical biology at GIS, Singapore
url: https://www.yucleiclab.com
theme: null
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

# Minimal Mistakes basics
minimal_mistakes_skin: default
locale: en
markdown: kramdown
kramdown:
  input: GFM
author:
  name: Yucleic Lab
nav:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Members
    url: /members/
  - title: Publications
    url: /publications/
  - title: Join Us
    url: /join/

collections:
  pages:
    output: true
    permalink: /:title/
